@echo off
:: ─────────────────────────────────────────────────────────────────
:: LocalWhisper — Install Universal Command
:: Installs 'localwhisper' command so you can run it from ANY terminal.
:: Run this ONCE: .\install.bat
:: ─────────────────────────────────────────────────────────────────

echo.
echo  ╔══════════════════════════════════════════════════╗
echo  ║   LocalWhisper — Universal Command Installer     ║
echo  ╚══════════════════════════════════════════════════╝
echo.

set "INSTALL_DIR=%USERPROFILE%\.localwhisper\bin"
set "PROJECT_DIR=%~dp0"

:: Remove trailing backslash from PROJECT_DIR
if "%PROJECT_DIR:~-1%"=="\" set "PROJECT_DIR=%PROJECT_DIR:~0,-1%"

:: Create install directory
if not exist "%INSTALL_DIR%" mkdir "%INSTALL_DIR%"

:: Create the launcher script
(
echo @echo off
echo :: LocalWhisper — Universal Launcher
echo :: Auto-generated by install.bat — do not edit manually
echo call "%PROJECT_DIR%\venv\Scripts\activate.bat"
echo python "%PROJECT_DIR%\main.py" %%*
) > "%INSTALL_DIR%\localwhisper.cmd"

echo [OK] Created launcher at: %INSTALL_DIR%\localwhisper.cmd

:: Add to PATH if not already there
echo %PATH% | findstr /I /C:"%INSTALL_DIR%" >nul 2>&1
if %ERRORLEVEL% neq 0 (
    :: Add to user PATH permanently (setx)
    for /f "tokens=2*" %%A in ('reg query "HKCU\Environment" /v Path 2^>nul') do set "CURRENT_USER_PATH=%%B"
    
    :: Check if already in user PATH
    echo %CURRENT_USER_PATH% | findstr /I /C:"%INSTALL_DIR%" >nul 2>&1
    if %ERRORLEVEL% neq 0 (
        if defined CURRENT_USER_PATH (
            setx PATH "%CURRENT_USER_PATH%;%INSTALL_DIR%" >nul 2>&1
        ) else (
            setx PATH "%INSTALL_DIR%" >nul 2>&1
        )
        echo [OK] Added to user PATH
        echo.
        echo  ⚠  Close and reopen your terminal for PATH changes to take effect.
    ) else (
        echo [OK] Already in user PATH
    )
) else (
    echo [OK] Already in current PATH
)

echo.
echo  ✓ Installation complete!
echo.
echo  Usage: Open ANY terminal and type:
echo.
echo      localwhisper
echo.
echo  The command will work from any directory.
echo.
pause
